# from tvm.script import ir as I
# from tvm.script import tir as T

@I.ir_module
class Module:
    @T.prim_func
    def main(Q: T.Buffer((1, 4, 2, 8), "float16"), K: T.Buffer((1, 4, 2, 8), "float16"), V: T.Buffer((1, 4, 2, 8), "float16"), Output: T.Buffer((1, 4, 2, 8), "float16")):
        T.func_attr({"K_shared": 147456, "O_shared": 114688, "Q_shared": 163840, "V_shared": 131072, "acc_o": 98304, "acc_s": 49152, "acc_s_cast": 180224, "coeff": 49152, "coeff_1": 32768, "logsum": 81920, "scores_max": 65536, "scores_max_prev": 32768, "scores_scale": 16384, "scores_sum": 196608, "table": 16384, "table_1": 0, "target": T.target({"arch": "sm_89", "host": {"keys": ["cpu"], "kind": "stackvm", "tag": ""}, "keys": ["cuda", "gpu"], "kind": "cuda", "max_num_threads": 1024, "tag": "", "thread_warp_size": 32}), "tmp_buffer_max": 81920, "tmp_buffer_sum": 65536, "work0": 0, "work0_1": 229376, "work1": 245760, "work1_1": 212992})
        Q_shared = T.decl_buffer((2, 8), "float16", scope="shared.dyn")
        acc_o = T.decl_buffer((2, 8), scope="shared.dyn")
        logsum = T.decl_buffer((2, 1), scope="shared.dyn")
        scores_max = T.decl_buffer((2, 1), scope="shared.dyn")
        K_shared = T.decl_buffer((2, 8), "float16", scope="shared.dyn")
        acc_s = T.decl_buffer((2, 2), scope="shared.dyn")
        scores_max_prev = T.decl_buffer((2, 1), scope="shared.dyn")
        tmp_buffer_max = T.decl_buffer((2, 32), scope="shared.dyn")
        scores_scale = T.decl_buffer((2, 1), scope="shared.dyn")
        work0 = T.decl_buffer((2, 1), scope="shared.dyn")
        work1 = T.decl_buffer((2, 1), scope="shared.dyn")
        coeff = T.decl_buffer((64, 32), scope="shared.dyn")
        table = T.decl_buffer((64, 192), scope="shared.dyn")
        work0_1 = T.decl_buffer((2, 2), scope="shared.dyn")
        work1_1 = T.decl_buffer((2, 2), scope="shared.dyn")
        coeff_1 = T.decl_buffer((64, 32), scope="shared.dyn")
        table_1 = T.decl_buffer((64, 192), scope="shared.dyn")
        scores_sum = T.decl_buffer((2, 1), scope="shared.dyn")
        tmp_buffer_sum = T.decl_buffer((2, 32), scope="shared.dyn")
        acc_s_cast = T.decl_buffer((2, 2), "float16", scope="shared.dyn")
        V_shared = T.decl_buffer((2, 8), "float16", scope="shared.dyn")
        O_shared = T.decl_buffer((2, 8), "float16", scope="shared.dyn")
        for bx, by in T.grid(2, 2):
            T.call_extern("handle", "ppl.copy", T.region(Q[0, bx * 2:bx * 2 + 2, by, 0:8], 1, 2, 8), T.region(Q_shared[0, 0], 2, 2, 8))
            T.call_extern("handle", "ppl.fill", T.tvm_access_ptr(T.type_annotation("float32"), acc_o.data, 0, 16, 2), T.float32(0))
            T.call_extern("handle", "ppl.fill", T.tvm_access_ptr(T.type_annotation("float32"), logsum.data, 0, 2, 2), T.float32(0))
            T.call_extern("handle", "ppl.fill", T.tvm_access_ptr(T.type_annotation("float32"), scores_max.data, 0, 2, 2), T.float32("-inf"))
            for k in range(2):
                T.call_extern("handle", "ppl.copy", T.region(K[0, k * 2:k * 2 + 2, by, 0:8], 1, 2, 8), T.region(K_shared[0, 0], 2, 2, 8))
                T.call_extern("handle", "ppl.fill", T.tvm_access_ptr(T.type_annotation("float32"), acc_s.data, 0, 4, 2), T.float32(0))
                T.call_extern("handle", "ppl.gemm", T.tvm_access_ptr(T.type_annotation("float16"), Q_shared.data, 0, 16, 1), T.tvm_access_ptr(T.type_annotation("float16"), K_shared.data, 0, 16, 1), T.tvm_access_ptr(T.type_annotation("float32"), acc_s.data, 0, 4, 3), T.bool(False), T.bool(True), 2, 2, 8)
                T.call_extern("handle", "ppl.copy", T.region(scores_max[0, 0], 1, 2, 1), T.region(scores_max_prev[0, 0], 2, 2, 1))
                T.call_extern("handle", "ppl.fill", T.tvm_access_ptr(T.type_annotation("float32"), scores_max.data, 0, 2, 2), T.float32("-inf"))
                T.call_extern("handle", "ppl.reduce_max", T.tvm_access_ptr(T.type_annotation("float32"), acc_s.data, 0, 4, 3), T.tvm_access_ptr(T.type_annotation("float32"), scores_max.data, 0, 2, 3), T.tvm_access_ptr(T.type_annotation("float32"), tmp_buffer_max.data, 0, 64, 3), 32, 32, 32)
                T.call_extern("handle", "ppl.sub", T.tvm_access_ptr(T.type_annotation("float32"), scores_scale.data, 0, 2, 2), T.tvm_access_ptr(T.type_annotation("float32"), scores_max_prev.data, 0, 2, 1), T.tvm_access_ptr(T.type_annotation("float32"), scores_max.data, 0, 2, 1))
                T.call_extern("handle", "ppl.mul_C", T.tvm_access_ptr(T.type_annotation("float32"), scores_scale.data, 0, 2, 2), T.tvm_access_ptr(T.type_annotation("float32"), scores_scale.data, 0, 2, 1), T.float32(0.51006972298409881))
                T.call_extern("handle", "ppl.exp", T.tvm_access_ptr(T.type_annotation("float32"), scores_scale.data, 0, 2, 3), T.tvm_access_ptr(T.type_annotation("float32"), work0.data, 0, 2, 3), T.tvm_access_ptr(T.type_annotation("float32"), work1.data, 0, 2, 3), T.tvm_access_ptr(T.type_annotation("float32"), coeff.data, 0, 2048, 3), T.tvm_access_ptr(T.type_annotation("float32"), table.data, 0, 12288, 3))
                T.call_extern("handle", "ppl.sub", T.tvm_access_ptr(T.type_annotation("float32"), acc_s.data, 0, 4, 2), T.tvm_access_ptr(T.type_annotation("float32"), acc_s.data, 0, 4, 1), T.tvm_access_ptr(T.type_annotation("float32"), scores_max.data, 0, 2, 1))
                T.call_extern("handle", "ppl.mul_C", T.tvm_access_ptr(T.type_annotation("float32"), acc_s.data, 0, 4, 2), T.tvm_access_ptr(T.type_annotation("float32"), acc_s.data, 0, 4, 1), T.float32(0.51006972298409881))
                T.call_extern("handle", "ppl.exp", T.tvm_access_ptr(T.type_annotation("float32"), acc_s.data, 0, 4, 3), T.tvm_access_ptr(T.type_annotation("float32"), work0_1.data, 0, 4, 3), T.tvm_access_ptr(T.type_annotation("float32"), work1_1.data, 0, 4, 3), T.tvm_access_ptr(T.type_annotation("float32"), coeff_1.data, 0, 2048, 3), T.tvm_access_ptr(T.type_annotation("float32"), table_1.data, 0, 12288, 3))
                T.call_extern("handle", "ppl.reduce_sum", T.tvm_access_ptr(T.type_annotation("float32"), acc_s.data, 0, 4, 3), T.tvm_access_ptr(T.type_annotation("float32"), scores_sum.data, 0, 2, 3), T.tvm_access_ptr(T.type_annotation("float32"), tmp_buffer_sum.data, 0, 64, 3), 32, 32, 32)
                T.call_extern("handle", "ppl.mul", T.tvm_access_ptr(T.type_annotation("float32"), logsum.data, 0, 2, 2), T.tvm_access_ptr(T.type_annotation("float32"), logsum.data, 0, 2, 1), T.tvm_access_ptr(T.type_annotation("float32"), scores_scale.data, 0, 2, 1))
                T.call_extern("handle", "ppl.add", T.tvm_access_ptr(T.type_annotation("float32"), logsum.data, 0, 2, 2), T.tvm_access_ptr(T.type_annotation("float32"), logsum.data, 0, 2, 1), T.tvm_access_ptr(T.type_annotation("float32"), scores_sum.data, 0, 2, 1))
                T.call_extern("handle", "ppl.copy", T.region(acc_s[0, 0], 1, 2, 2), T.region(acc_s_cast[0, 0], 2, 2, 2))
                T.call_extern("handle", "ppl.mul", T.tvm_access_ptr(T.type_annotation("float32"), acc_o.data, 0, 16, 2), T.tvm_access_ptr(T.type_annotation("float32"), acc_o.data, 0, 16, 1), T.tvm_access_ptr(T.type_annotation("float32"), scores_scale.data, 0, 2, 1))
                T.call_extern("handle", "ppl.copy", T.region(V[0, k * 2:k * 2 + 2, by, 0:8], 1, 2, 8), T.region(V_shared[0, 0], 2, 2, 8))
                T.call_extern("handle", "ppl.gemm", T.tvm_access_ptr(T.type_annotation("float16"), acc_s_cast.data, 0, 4, 1), T.tvm_access_ptr(T.type_annotation("float16"), V_shared.data, 0, 16, 1), T.tvm_access_ptr(T.type_annotation("float32"), acc_o.data, 0, 16, 3), T.bool(False), T.bool(False), 2, 8, 2)
            T.call_extern("handle", "ppl.div", T.tvm_access_ptr(T.type_annotation("float32"), acc_o.data, 0, 16, 2), T.tvm_access_ptr(T.type_annotation("float32"), acc_o.data, 0, 16, 1), T.tvm_access_ptr(T.type_annotation("float32"), logsum.data, 0, 2, 1))
            T.call_extern("handle", "ppl.copy", T.region(acc_o[0, 0], 1, 2, 8), T.region(O_shared[0, 0], 2, 2, 8))
            T.call_extern("handle", "ppl.copy", T.region(O_shared[0, 0], 1, 2, 8), T.region(Output[0, bx * 2:bx * 2 + 2, by, 0:8], 2, 2, 8))